### ISSUE TITLE
Document the package dependencies for building

### ISSUE THREAD

**Issue by nmenon** [tomba/rwmem#2]
apt-get install cmake pkg-config cmake-data python3-dev  was needed on debian stretch.
$ git branch -v
- master ab38cf4 Add option to build with -static
  $  git clean -fdx;git reset --hard;cmake .;make
  HEAD is now at ab38cf4 Add option to build with -static
  -- The C compiler identification is GNU 6.1.1
  -- The CXX compiler identification is GNU 6.1.1
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Setting build type to 'Release' as none was specified.
  -- Performing Test HAS_LTO_FLAG
  -- Performing Test HAS_LTO_FLAG - Success
  -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
  -- Checking for module 'python3'
  --   Found python3, version 3.5
  -- Configuring done
  CMake Error at rwmem/CMakeLists.txt:8 (add_executable):
  Cannot find source file:
  
    /root/rwmem/ext/inih/ini.c
  
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

-- Generating done
-- Build files have been written to: /root/rwmem
Scanning dependencies of target rwmem-lib
[ 10%] Building CXX object librwmem/CMakeFiles/rwmem-lib.dir/helpers.cpp.o
[ 20%] Building CXX object librwmem/CMakeFiles/rwmem-lib.dir/i2ctarget.cpp.o
[ 30%] Building CXX object librwmem/CMakeFiles/rwmem-lib.dir/mappedregs.cpp.o
[ 40%] Building CXX object librwmem/CMakeFiles/rwmem-lib.dir/mmaptarget.cpp.o
[ 50%] Building CXX object librwmem/CMakeFiles/rwmem-lib.dir/regfiledata.cpp.o
[ 60%] Building CXX object librwmem/CMakeFiles/rwmem-lib.dir/regs.cpp.o
[ 70%] Linking CXX static library ../lib/librwmem.a
[ 70%] Built target rwmem-lib
Scanning dependencies of target rwmem-bin
[ 80%] Linking CXX executable ../bin/rwmem
/usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/crt1.o: In function `_start':
(.text+0x28): undefined reference to`main'
collect2: error: ld returned 1 exit status
rwmem/CMakeFiles/rwmem-bin.dir/build.make:69: recipe for target 'bin/rwmem' failed
make[2]: **\* [bin/rwmem] Error 1
CMakeFiles/Makefile2:172: recipe for target 'rwmem/CMakeFiles/rwmem-bin.dir/all' failed
make[1]: **\* [rwmem/CMakeFiles/rwmem-bin.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by nmenon** [comment]
Probably also needs using https:// instead of git:// and git submodule init and git submodule update instructions since it is not automagically being done..

**Comment by tomba** [comment]
Pushed 8addbc6de75c7f72e609fe47c8286e38cd389845
